version: '3'
services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    ports:
      - "49154:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
